version: "3.7"

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      loki_net:
        ipv4_address: 172.28.0.2

  nginx:
    image: nginx:latest
    container_name: nginx-loki
    depends_on:
      - loki
    ports:
      - "3100:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      loki_net:
        ipv4_address: 172.28.0.3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/var/provisioning
    volumes:
      - ./grafana:/var/provisioning:ro
    networks:
      loki_net:
        ipv4_address: 172.28.0.4

networks:
  loki_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
